remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dr.-Ing. Milan Babić
description: Inactive Co-Founder / Investor
show_downloads: "false"
logo: "/img/MilanBabic_IEEE.jpg"  # Change this to the path of your logo
